In [9]:
#pip install numpy


In [10]:
#! pip install numpy

In [11]:
#@ pip install numpy

In [12]:
print("hello")

hello


## Numpy
NumPy is the core numerical computing library for Python, widely used for:

##### Fast array and matrix operations
##### Linear algebra
##### Random number generation
##### Scientific computing
##### Data analysis and machine learning foundations

In [13]:
import numpy as np  # as- is a keyword  used to create a shorter nickname (an alias)for a library.

In [14]:
np.__version__

'2.4.6'

In [15]:
lst = list(range(1,10))

In [16]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
type(lst)

list

In [18]:
arr = np.array(lst)  # used to convert list into array

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr = np.array([2,4,7,8,9,332,6,5,4,6,4,77,44,31])
arr

array([  2,   4,   7,   8,   9, 332,   6,   5,   4,   6,   4,  77,  44,
        31])

In [22]:
arr = np.array([range(1,20)])
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]])

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr = np.arange(1,21)  ## use range in array

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
arr = np.zeros(10)  ## used to print zeores

In [27]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
arr = np.ones(10)

In [29]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
arr = np.zeros((5,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.zeros((5,10))
print(arr.ndim)   ## checking dimensions of array

2


In [32]:
arr = np.linspace(1,10,5) # linespace is used to give the samples.
print(arr)                # 1 is starting value of sequence,10 is the end value of the sequence
print(type(arr))          # 5 is the total no. of sample sequence

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [33]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
arr = arr.reshape(10,3)
arr           ## reshape is used to turn 1d array to 2d array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [35]:
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
np.random.randint(1,5,10)  ## used to genrate random values
 # 1 is starting point
 # 5 is range at which element should be
 # and 10 is no. elments we want

array([1, 3, 1, 2, 3, 2, 1, 4, 2, 3], dtype=int32)

In [37]:
np.random.randint(1,5,(5,6)) #this will create  random 2d array  

array([[4, 1, 1, 2, 1, 1],
       [1, 1, 4, 1, 3, 2],
       [2, 2, 4, 2, 2, 1],
       [1, 2, 2, 2, 4, 3],
       [3, 3, 1, 1, 4, 3]], dtype=int32)

In [38]:
arr = np.random.random(10)  # used to generating random 10 number of items

In [39]:
arr

array([0.65053032, 0.57766517, 0.5213226 , 0.63800162, 0.5371209 ,
       0.87756128, 0.0422718 , 0.34561451, 0.51047205, 0.91785778])

In [40]:
arr = np.random.random((10,3))  # gentating random 2d array by using random
arr

array([[0.71660574, 0.39959387, 0.58705757],
       [0.70772914, 0.08450739, 0.06714963],
       [0.89629337, 0.17151094, 0.77703144],
       [0.61231002, 0.28376418, 0.61703752],
       [0.34777481, 0.57115346, 0.08958024],
       [0.07432014, 0.41092538, 0.81110387],
       [0.16979848, 0.42795651, 0.12473684],
       [0.79242982, 0.66026215, 0.69330258],
       [0.16785433, 0.58134334, 0.69996038],
       [0.68565624, 0.04728832, 0.22560114]])

In [41]:
arr = np.arange(60).reshape(12,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [42]:
print("size of array:-",arr.size)  ## this all are attributes of array
## size of element
print("shape of array:-",arr.shape) ## shape
print("datatype of array:-",arr.dtype)  # datatype
print("number of dimension :-",arr.ndim)  # no. of dimension

size of array:- 60
shape of array:- (12, 5)
datatype of array:- int64
number of dimension :- 2


In [43]:
lst = [[2,5,6],[7,8,3]]
lst

[[2, 5, 6], [7, 8, 3]]

In [44]:
arr = np.array(lst)
arr


array([[2, 5, 6],
       [7, 8, 3]])

In [45]:
arr = np.arange(60).reshape(12,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [46]:
arr.shape

(12, 5)

In [47]:
arr.T  ## transpose the array

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [48]:
## indexing and slicing
arr[0,0]  

np.int64(0)

In [49]:
arr[0][0]

np.int64(0)

In [50]:
arr[11,4]

np.int64(59)

In [51]:
arr[-1,-1]

np.int64(59)

In [52]:
arr[11,-1]

np.int64(59)

In [53]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [55]:
arr[5:7,3:5]

array([[28, 29],
       [33, 34]])

In [56]:
arr[0:10,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48]])

In [57]:
arr[-1,-1]
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [58]:
arr.transpose()  ## arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [59]:
arr.shape

(12, 5)

In [60]:
arr.size

60

In [61]:
arr.dtype

dtype('int64')

In [62]:
arr.ndim

2

#### Working on 3d array

In [65]:
arr = np.arange(225).reshape(5,15,3)  # for 3d array 5 denotes table
# 15 is row of every table
# 3 is denoting every column of table
arr


array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
arr[0][0]  # for first table

array([0, 1, 2])

In [68]:
arr[0][0][0]  # for first element

np.int64(0)

In [69]:
arr[-1]  # giving last table

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [70]:
arr[-2]  # giving second last table

array([[135, 136, 137],
       [138, 139, 140],
       [141, 142, 143],
       [144, 145, 146],
       [147, 148, 149],
       [150, 151, 152],
       [153, 154, 155],
       [156, 157, 158],
       [159, 160, 161],
       [162, 163, 164],
       [165, 166, 167],
       [168, 169, 170],
       [171, 172, 173],
       [174, 175, 176],
       [177, 178, 179]])

In [71]:
arr[0:5,0]  # for first row of table

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [74]:
arr[0:5,0,0]   # first element of tables

array([  0,  45,  90, 135, 180])

In [75]:
arr[0:5,0:1,0:1] # first element of tables it is done

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [78]:
arr[0:5,2:4,0:3]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [79]:
arr[0:5,-1,0]

array([ 42,  87, 132, 177, 222])

In [82]:
arr[0:5,0:15,2:4]

array([[[  2],
        [  5],
        [  8],
        [ 11],
        [ 14],
        [ 17],
        [ 20],
        [ 23],
        [ 26],
        [ 29],
        [ 32],
        [ 35],
        [ 38],
        [ 41],
        [ 44]],

       [[ 47],
        [ 50],
        [ 53],
        [ 56],
        [ 59],
        [ 62],
        [ 65],
        [ 68],
        [ 71],
        [ 74],
        [ 77],
        [ 80],
        [ 83],
        [ 86],
        [ 89]],

       [[ 92],
        [ 95],
        [ 98],
        [101],
        [104],
        [107],
        [110],
        [113],
        [116],
        [119],
        [122],
        [125],
        [128],
        [131],
        [134]],

       [[137],
        [140],
        [143],
        [146],
        [149],
        [152],
        [155],
        [158],
        [161],
        [164],
        [167],
        [170],
        [173],
        [176],
        [179]],

       [[182],
        [185],
        [188],
        [191],
        [194],
        [197],
  

In [84]:
arr[0:5,0:15,3:5]

array([], shape=(5, 15, 0), dtype=int64)

In [86]:
arr[0:5,-1,-1]

array([ 44,  89, 134, 179, 224])

In [94]:
arr[0:5,14:15,-1]

array([[ 44],
       [ 89],
       [134],
       [179],
       [224]])

In [95]:
arr[0:5,14:15,2]

array([[ 44],
       [ 89],
       [134],
       [179],
       [224]])

In [96]:
arr[0:5,-1,2:3]

array([[ 44],
       [ 89],
       [134],
       [179],
       [224]])

In [93]:
print("size of array:-",arr.size)  ## this all are attributes of array
## size of element
print("shape of array:-",arr.shape) ## shape
print("datatype of array:-",arr.dtype)  # datatype
print("number of dimension :-",arr.ndim)  # no. of dimension

size of array:- 225
shape of array:- (5, 15, 3)
datatype of array:- int64
number of dimension :- 3


In [101]:
arr[0,-1,-1]= 35  # for replacing the element replce last element of first table
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  35]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [102]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [113]:
arr1 = np.array([100, 20, 19, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

arr1.sort()
#print(arr1.sort())  # it will return none
arr1


Array 1 : [100  20  19  40]
Array 2 : [2 4 6 8]


array([ 19,  20,  40, 100])

In [112]:
arr= np.arange(225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [114]:
arr = arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11